### ISSUE TITLE
Task: Setting Arduino and Test Sensors

### ISSUE THREAD

**Issue by asha97** [asha97/COEN_ELEC_390_Project#19]

**Comment by asha97** [comment]
Steps to follow

**Step 1:** Connect to Arduino IDE 
**Step 2:** Connect ESP32 to wifi
**Step 3:** Connect each sensor 1 by one
**Step 4:** Merge all sensor codes
**Step 5:** Connect to firebase

**Comment by pavithrasiv** [comment]
All sensors have been connected and data is being displayed onto firebase's real-time database. Therefore, this issue can be closed.
